// packages/app-next-alt/src/components/Button.tsx
import React from 'react'
import { Link, LinkProps } from 'react-router-dom'
import styled, { css } from 'styled-components'
import { WithCssProps, WithMarginProps, WithMarginStyles } from 'utilities/withProps'

interface BaseProps {
  variant?: 'normal' | 'info' | 'warning' | 'alarm'
  size?: 's'
  border?: boolean
  round?: boolean
  type?: 'button' | 'submit'
}

type WithBaseProps = WithCssProps<WithMarginProps<BaseProps>>
type ButtonProps = React.HTMLAttributes<HTMLButtonElement> & WithBaseProps
type ButtonLinkProps = LinkProps & WithBaseProps

const defaultProps: BaseProps = {
  border: false,
  round: false,
}

const BaseStyles = css<BaseProps>`
  ${WithMarginStyles}

  --base-color: ${({ theme, border }) => (border ? theme.colors.white : theme.colors.green)};
  --text-color: ${(props) => props.theme.colors.white};
  --shadow: var(--base-color);

  position: relative;
  background-color: ${(props) => (props.border ? 'transparent' : 'var(--base-color)')};
  border-radius: ${(props) => (props.round ? '100%' : props.theme.baseRadius)};
  border: 2px solid var(--base-color);
  box-shadow: ${(props) => (props.border ? 'none' : '0 2px 9px var(--shadow)')};
  color: var(--text-color);
  text-decoration: none;
  font-family: var(--font-normal);
  text-align: center;
  font-weight: 500;
  font-size: ${(props) => props.theme.fonts.base};
  display: inline-flex;
  justify-content: center;
  align-items: center;
  cursor: pointer;
  padding: ${(props) => {
    if (props.round) {
      if (props.size === 's') {
        return `calc(0.5 * ${props.theme.spacings.m})`
      }
      return props.theme.spacings.m
    }
    return props.size === 's'
      ? `calc(0.5 * ${props.theme.spacings.m}) ${props.theme.spacings.m}`
      : `calc(2 * ${props.theme.spacings.m})`
  }};

  ${(props) =>
    props.variant === 'normal' &&
    css`
      --base-color: ${(props) => props.theme.colors.green};
    `}

  ${(props) =>
    props.variant === 'info' &&
    css`
      --base-color: ${(props) => props.theme.colors.blue};
    `}

  ${(props) =>
    props.variant === 'warning' &&
    css`
      --base-color: ${(props) => props.theme.colors.yellow};
      --text-color: ${(props) => props.theme.colors.greenDark};
    `}

  ${(props) =>
    props.variant === 'alarm' &&
    css`
      --base-color: ${(props) => props.theme.colors.red};
    `}

  &:hover {
    text-decoration: underline;
  }

  &[disabled],
  &[aria-disabled='true'] {
    cursor: not-allowed;
  }

  &:focus:not([disabled]),
  &:active:not([aria-disabled]) {
    border-color: ${(props) => props.theme.colors.white};
    outline: none;
  }

  & > svg {
    width: 20px;
    height: 20px;
    margin-right: ${({ theme, round }) => !round && theme.spacings.m};
  }
`

const ButtonContainer = styled.button<BaseProps>`
  ${BaseStyles}
`

const LinkContainer = styled(({ variant, border, ...props }) => <Link {...props} />)<BaseProps>`
  ${BaseStyles}
`

export function ButtonLink(props: ButtonLinkProps) {
  return <LinkContainer {...props} />
}

ButtonLink.defaultProps = defaultProps

export function Button(props: ButtonProps) {
  return <ButtonContainer {...props} />
}

Button.defaultProps = defaultProps

// packages/landing/components/Button.vue
<template>
  <component
    :is="tag"
    :type="buttonType"
    :class="[color, type]"
  >
    <div v-if="$slots.icon || $scopedSlots.icon" :class="getIconClass()">
      <slot name="icon" />
    </div>

    <span v-if="$slots.default || $scopedSlots.default">
      <slot />
    </span>
  </component>
</template>

<script>
  const colors = ['plain', 'grey', 'default', 'yellow', 'red', 'blue', 'transparent']
  const types = ['normal', 'circle', 'small']
  const tags = ['button', 'a']

  export default {
    name: 'Button',

    props: {
      tag: {
        type: String,
        default: 'button',
        validator: v => tags.includes(v)

      },
      color: {
        type: String,
        default: 'default',
        validator: v => colors.includes(v)
      },
      type: {
        type: [String, Array],
        default: 'normal',
        validator: value => {
          if (value === 'submit') return value
          return Array.isArray(value)
            ? value.every(v => types.includes(v))
            : types.includes(value)
        }
      }
    },

    computed: {
      buttonType () {
        if (this.tag === 'a') return
        return this.type === 'submit' ? this.type : 'button'
      }
    },

    methods: {
      getIconClass () {
        return ['button-icon', {
          single: !this.$scopedSlots.default
        }]
      }
    }
  }
</script>

<style lang="postcss" scoped>
  button,
  a {
    --button-padding: 6px;
    --button-circle-size: 50px;
    --button-background: var(--brand-green);
    --button-focus: var(--brand-green-low);
    --button-icon: var(--text-color-button);
    --button-shadow: var(--brand-green-medium);
    --button-font-size: var(--text-size-base);
    --text-color: var(--text-color-button);

    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    background: var(--button-background);
    font-family: var(--font-family);
    font-size: var(--button-font-size);
    font-weight: 500;
    text-decoration: none;
    color: var(--text-color);
    border: none;
    border-radius: var(--border-radius);
    padding: calc(2 * var(--button-padding)) calc(3 * var(--button-padding));
    transition: background-color 100ms var(--ease-out-back);
    box-shadow: 0 2px 9px var(--button-shadow);

    &::after {
      opacity: 0;
      content: "";
      position: absolute;
      width: calc(100% + 8px);
      height: calc(100% + 8px);
      top: 0;
      left: 0;
      transform: translate(-4px, -4px);
      border-radius: var(--border-radius);
      background: transparent;
      border: 6px solid var(--button-focus);
      z-index: 0;
    }

    &:hover {
      text-decoration: underline;
    }

    &:active,
    &:focus {
      outline: none;
      text-decoration: none;
    }

    &:active::after,
    &:focus::after {
      opacity: 1;
    }

    & span {
      color: var(--text-color);
      font-family: inherit;
    }

    & .button-icon {
      width: var(--icon-size-base);
      height: var(--icon-size-base);
      display: flex;
      align-items: center;

      &:not(.single) {
        margin-right: calc(var(--base-gap) / 2);
      }
    }

    & .button-icon svg,
    & svg {
      width: var(--icon-size-base);
      height: var(--icon-size-base);
    }
  }

  button.circle,
  a.circle {
    border-radius: 50%;
    width: var(--button-circle-size);
    height: var(--button-circle-size);
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 0;

    & .button-icon svg {
      margin: 0 auto;
    }

    &::after {
      border-radius: 50%;
    }
  }

  button.small,
  a.small {
    --button-padding: 4px;
    --button-circle-size: 35px;

    & .button-icon {
      transform: scale(0.95);
    }
  }

  button.disabled,
  a.disabled,
  button[disabled],
  a[disabled] {
    --button-background: var(--grey);
    --button-shadow: var(--grey);
    color: var(--dark-grey);
    cursor: not-allowed;

    & .button-icon svg {
      filter: invert(100%);
    }
  }

  button.plain,
  a.plain {
    --button-background: var(--grey);
    --button-focus: var(--dark-grey);
    --button-shadow: var(--grey);
    --text-color: var(--link-color);

    @nest html[data-theme="dark"] & {
      --button-background: var(--dark-grey);
      --button-focus: var(--grey);
      --text-color: white;
    }
  }

  button.yellow,
  a.yellow {
    --button-background: var(--brand-yellow);
    --button-focus: var(--brand-yellow-low);
    --button-shadow: var(--brand-yellow-medium);
    --text-color: var(--link-color);
  }

  button.red,
  a.red {
    --button-background: var(--brand-red);
    --button-focus: var(--brand-red-low);
    --button-shadow: var(--brand-red-medium);
  }

  button.blue,
  a.blue {
    --button-background: var(--brand-blue);
    --button-focus: var(--brand-blue-low);
    --button-shadow: var(--brand-blue-medium);
  }

  button.grey,
  a.grey {
    --button-background: var(--dark-grey);
    --button-focus: var(--grey);
    --button-shadow: var(--dark-grey);
  }

  button.transparent,
  a.transparent {
    --button-background: transparent;
    --button-focus: transparent;
    --button-shadow: transparent;

    & .button-icon svg {
      filter: invert(100%);

      @nest html[data-theme="dark"] & {
        filter: invert(0);
      }
    }
  }
</style>
