// packages/app-next-alt/src/components/AppHeader.tsx
import React from 'react'
import styled from 'styled-components'
import { createTeleporter } from 'react-teleporter'
import { Link, useHistory } from 'react-router-dom'
import { ArrowLeft } from 'react-feather'
import { theme } from 'theme'
import { routePaths } from 'routes'
import { Heading } from './Typography'
import VisuallyHidden from './VisuallyHidden'
import AppLogo from './AppLogo'

export const AppHeaderPortal = createTeleporter()

const AppHeaderContainer = styled.header<{ backgroundColor?: AppHeaderColor }>`
  width: 100%;
  height: ${(props) => props.theme.frameWidgetHeight};
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-shrink: 0;
  position: sticky;
  top: 0;
  z-index: 1;
  background-color: ${(props) =>
    props.backgroundColor === undefined
      ? 'transparent'
      : props.theme.colors[props.backgroundColor]};

  & > div {
    display: grid;
    align-items: center;
    height: 100%;
    grid-template-columns: auto auto;
  }

  & > h1 {
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
  }
`

const AppHeaderIcon = styled.div`
  height: 100%;
  min-width: ${(props) => props.theme.frameWidgetHeight};
  display: flex;
  justify-content: center;
  align-items: center;

  & > a,
  & > button {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
    border: none;
    background: transparent;

    &:focus {
      outline: none;
      background: ${(props) => props.theme.colors.white};
      border-bottom-right-radius: ${(props) => props.theme.baseRadius};
    }
  }
`

export type AppHeaderColor = 'green' | 'blue'

export type AppHeaderProps = React.PropsWithChildren<{
  color?: AppHeaderColor
}>

export default function AppHeader(props: AppHeaderProps) {
  const history = useHistory()
  const { color, children } = props
  const textColor = color === undefined ? 'greenDark' : 'white'
  const hasRouteTitle = React.Children.count(children) > 0
  const showBackButton = history.location.pathname.split('/').filter(Boolean).length > 1

  return (
    <AppHeaderContainer backgroundColor={color}>
      <AppHeaderIcon>
        {showBackButton ? (
          <button
            onClick={() =>
              history.location.pathname === routePaths.login
                ? history.push(routePaths.root)
                : history.goBack()
            }
            data-cy="app-header-return"
          >
            <ArrowLeft color={theme.colors[textColor]} aria-hidden="true" focusable="false" />
            <VisuallyHidden>Back</VisuallyHidden>
          </button>
        ) : (
          <Link to={routePaths.root}>
            <AppLogo color={textColor} inverse={textColor !== 'greenDark'} />
          </Link>
        )}
      </AppHeaderIcon>

      <Heading color={textColor} as="h1" bold>
        {hasRouteTitle ? children : 'HappyPlants'}
      </Heading>

      <AppHeaderPortal.Target />
    </AppHeaderContainer>
  )
}

// packages/app-next/src/components/AppHeader.vue
<template>
  <header id="app-header" :class="[color]">
    <div class="app-header-essentials">
      <div class="app-header-icon">
        <router-link v-if="returnTo" :to="returnTo" data-cy="app-header-return">
          <feather-left />
          <v-text class="visuallyhidden" color="inactive">Back</v-text>
        </router-link>
        <app-logo :color="color" v-else />
      </div>

      <v-text type="subtitle" :color="titleColor" class="app-header-title">
        <slot>HappyPlants</slot>
      </v-text>
    </div>

    <slot name="actions" />
  </header>
</template>

<script lang="ts">
  import Vue from 'vue'

  export default Vue.extend({
    name: 'AppHeader',

    components: {
      'feather-left': () =>
        import('vue-feather-icons/icons/ArrowLeftIcon' /* webpackChunkName: "icons" */),
    },

    props: {
      returnTo: {
        type: [String, Boolean],
        default: false,
      },
      color: {
        type: String,
        default: 'green',
        validator: (v) => ['white', 'green'].includes(v),
      },
    },

    computed: {
      titleColor(): string {
        if (this.color === 'white') {
          return 'special'
        }
        return 'normal'
      },
    },
  })
</script>

<style lang="postcss" scoped>
  #app-header {
    width: 100%;
    height: var(--app-header-height);
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-shrink: 0;
    position: sticky;
    top: 0;
    z-index: 1;

    & .app-header-essentials {
      display: grid;
      align-items: center;
      height: 100%;
      grid-template-columns: auto auto;
    }
  }

  .app-header-icon {
    height: 100%;
    min-width: var(--app-header-height);
    display: flex;
    justify-content: center;
    align-items: center;

    @nest .green & svg:not(#app-logo) {
      stroke: var(--brand-green-dark);
    }

    @nest .white & svg:not(#app-logo) {
      stroke: var(--brand-white);
    }

    & > a {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 100%;
      height: 100%;

      &:focus {
        outline: none;
        background: var(--brand-white);
        border-bottom-right-radius: var(--base-radius);
      }
    }
  }

  .app-header-title {
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    font-weight: 700 !important;
  }
</style>
