// packages/app-next/src/shared/components/Button.vue
<template>
  <button :class="btnClass">
    <slot />
  </button>
</template>

<script lang="ts">
  import Vue from 'vue'

  const colors = ['green', 'blue', 'yellow', 'red', 'grey']

  export default Vue.extend({
    name: 'VButton',

    props: {
      color: {
        type: String,
        default: 'green',
        validator: v => colors.includes(v),
      },
      small: {
        type: Boolean,
        default: false,
      },
      border: {
        type: Boolean,
        default: false,
      },
    },

    computed: {
      btnClass(): string[] {
        return ['btn', this.color, this.small && 'small', this.border && 'border']
      },
    },
  })
</script>

<style lang="postcss">
  .btn {
    --background: var(--brand-green);
    --shadow: var(--brand-green);
    background: var(--background);
    border-radius: var(--base-radius);
    color: var(--brand-white);
    font-weight: 500;
    font-size: var(--text-size-base);
    border: 2px solid var(--background);
    padding: 13.5px var(--base-gap);
    box-shadow: 0 2px 9px var(--shadow);
    text-decoration: none;
    text-align: center;
    display: inline-flex;
    justify-content: center;
    align-items: center;
    transition: border-color 100ms ease-in-out, box-shadow 100ms ease-in-out;

    &:focus {
      animation: bounce 650ms;
    }

    &:focus:not(.border),
    &:active:not(.border) {
      border-color: var(--brand-white);
      outline: none;
    }

    /* Icons */
    & > svg {
      width: 20px;
      height: 20px;
      margin-right: calc(0.5 * var(--base-gap));
    }

    /* Type */
    &.border {
      background: transparent !important;
      border: 2px solid var(--brand-white);
      box-shadow: none;

      &:focus,
      &:active {
        --shadow: var(--brand-white);
        box-shadow: 0 2px 9px var(--shadow);
        outline: none;
      }

      &.yellow {
        color: var(--brand-white);
      }
    }

    /* Size */
    &.small {
      padding: calc(var(--base-gap) / 2.5) 10px;
    }

    /* Color */
    &.blue {
      --background: var(--brand-blue);
      --shadow: var(--brand-blue);
    }

    &.yellow {
      --background: var(--brand-yellow);
      --shadow: var(--brand-yellow);
      color: var(--brand-green-dark);
    }

    &.red {
      --background: var(--brand-red);
      --shadow: var(--brand-red);
    }

    &.grey,
    &[disabled],
    &[aria-disabled] {
      --background: var(--brand-beige-dark);
      --shadow: var(--brand-beige-dark);
      box-shadow: none;
    }

    &.grey:focus,
    &.gey:active {
      box-shadow: 0 2px 9px var(--shadow);
    }
  }
</style>

// packages/app-next-alt/src/components/Button.tsx
import React from 'react'
import { Link, LinkProps } from 'react-router-dom'
import styled, { css } from 'styled-components'
import { WithCssProps, WithMarginProps, WithMarginStyles } from 'utilities/withProps'

interface BaseProps {
  variant?: 'normal' | 'info' | 'warning' | 'alarm'
  size?: 's'
  border?: boolean
}

type WithBaseProps = WithCssProps<WithMarginProps<BaseProps>>
type ButtonProps = React.HTMLAttributes<HTMLButtonElement> & WithBaseProps
type ButtonLinkProps = LinkProps & WithBaseProps

const BaseStyles = css<BaseProps>`
  ${WithMarginStyles}

  --base-color: ${({ theme, border }) => (border ? theme.colors.white : theme.colors.green)};
  --shadow: var(--base-color);

  position: relative;
  background-color: ${(props) => (props.border ? 'transparent' : 'var(--base-color)')};
  border-radius: ${(props) => props.theme.baseRadius};
  border: 2px solid var(--base-color);
  box-shadow: ${(props) => (props.border ? 'none' : '0 2px 9px var(--shadow)')};
  color: ${(props) => props.theme.colors.white};
  text-decoration: none;
  font-family: var(--font-normal);
  text-align: center;
  font-weight: 500;
  font-size: ${(props) => props.theme.fonts.base};
  display: inline-flex;
  justify-content: center;
  align-items: center;
  cursor: pointer;
  padding: ${(props) =>
    props.size === 's'
      ? `calc(0.5 * ${props.theme.spacings.m}) ${props.theme.spacings.m}`
      : `${props.theme.spacings.m} calc(2 * ${props.theme.spacings.m})`};

  ${(props) =>
    props.variant === 'normal' &&
    css`
      --base-color: ${(props) => props.theme.colors.green};
    `}

  ${(props) =>
    props.variant === 'info' &&
    css`
      --base-color: ${(props) => props.theme.colors.blue};
    `}

  ${(props) =>
    props.variant === 'warning' &&
    css`
      --base-color: ${(props) => props.theme.colors.yellow};
      color: ${(props) => props.theme.colors.greenDark};
    `}

  ${(props) =>
    props.variant === 'alarm' &&
    css`
      --base-color: ${(props) => props.theme.colors.red};
    `}

  &[disabled],
  &[aria-disabled="true"] {
    cursor: not-allowed;
  }

  &:focus:not([disabled]),
  &:active:not([aria-disabled]) {
    border-color: ${(props) => props.theme.colors.white};
    outline: none;
  }

  & > svg {
    width: 20px;
    height: 20px;
    margin-right: ${({ theme }) => theme.spacings.m};
  }
`

const ButtonContainer = styled.button<BaseProps>`
  ${BaseStyles}
`

export const StyledLink = styled(({ variant, border, ...props }) => <Link {...props} />)<BaseProps>`
  ${BaseStyles}
`

export function ButtonLink(props: ButtonLinkProps) {
  return <StyledLink {...props} />
}

ButtonLink.defaultProps = { border: false }

export function Button(props: ButtonProps) {
  return <ButtonContainer {...props} />
}

Button.defaultProps = { border: false }
