// src/components/Dialog.vue
<template>
  <div v-if="show" class="dialog-backdrop" @click.self="emitDialogClose">
    <section :style="{ backgroundColor }">
      <header class="dialog-header">
        <button
          aria-label="Close"
          class="circle inverse"
          @click.prevent="emitDialogClose">
          <feather-x width="18" height="18" />
        </button>
        <slot name="headline"></slot>
      </header>

      <div class="dialog-content">
        <slot name="content"></slot>
        <div class="dialog-actions">
          <slot name="cancel"></slot>
          <slot name="confirm"></slot>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
  export default {
    name: 'Dialog',

    props: {
      show: { type: Boolean, default: false },
      backgroundColor: { type: String, default: '#F5F5F5' }
    },

    components: {
      'feather-x': () =>
        import('vue-feather-icon/components/x' /* webpackChunkName: "general" */)
    },

    watch: {
      show () {
        if (this.show) {
          this.$root.$el.parentNode.classList.add('js-no-scrolling')
        } else {
          this.$root.$el.parentNode.classList.remove('js-no-scrolling')
        }
      }
    },

    methods: {
      emitDialogClose () {
        this.$emit('close-dialog')
      }
    }
  }
</script>

<style lang="scss" scoped>
  @import "~styles/colors";
  @import "~styles/fonts";
  @import "~styles/layout";
  @import "~styles/z-index";

  .dialog-backdrop {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    min-height: 100vh;
    height: 100%;
    background: rgba(0, 0, 0, 0.46);
    position: fixed;
    top: 0;
    left: 0;
    z-index: z($page-elements, modals);
  }

  section {
    width: auto;
    max-width: 85vw;
    background: $background-secondary;
    box-shadow: $plain-shadow;
    padding: $base-gap;
    border-radius: $border-radius;
  }

  .dialog-header {
    display: flex;
    align-items: flex-start;
    margin-bottom: $base-gap;

    button {
      margin-right: $base-gap + 5;
      background: $background-primary;
      color: $link-color;
      box-shadow: $plain-shadow;
    }

    h1 {
      font-size: $text-size-large;
      font-weight: 600;
      line-height: 115%;
      margin-top: 8px;
    }
  }

  .dialog-actions {
    display: flex;
    margin-top: $base-gap;

    button:first-of-type {
      margin-right: $base-gap*2;
    }
  }
</style>

// packages/app-next-alt/src/components/Dialog.tsx
import React from 'react'
import { A11yDialog } from 'react-a11y-dialog'
import A11yDialogInstance from 'a11y-dialog'
import { X } from 'react-feather'
import { createGlobalStyle } from 'styled-components'
import { theme } from 'theme'
import { HeadingBaseStyles } from './Typography'

export type Events = {
  show: () => void
  hide: () => void
}

export type DialogProps = React.PropsWithChildren<{
  id: string
  title: string
  reference: (instance: A11yDialogInstance) => void
}>

const DialogStyles = createGlobalStyle`
  .dialog-container,
  .dialog-overlay {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
  }

  .dialog-container {
    z-index: 2;
    display: flex;

    &[aria-hidden='true'] {
      display: none;
    }
  }

  .dialog-overlay {
    background-color: rgba(10, 62, 43, 0.8);
  }

  .dialog-content {
    margin: auto;
    margin-left: ${({ theme }) => theme.spacings.m};
    margin-right: ${({ theme }) => theme.spacings.m};
    z-index: 2;
    position: relative;
    width: 100%;
    background-color: ${({ theme }) => theme.colors.beige};
    border-radius: ${({ theme }) => theme.baseRadius};
    padding: ${({ theme }) => theme.spacings.m};
    display: grid;
    grid-template-columns: 1fr min-content;
    grid-template-areas:
      "title close"
      "content content";

    > div {
      grid-area: content;
      overflow: scroll;
      max-height: 70vh;
      padding-bottom: ${({ theme }) => theme.spacings.m};
    }
  }

  .dialog-close-button {
    grid-area: close;
    background-color: ${({ theme }) => theme.colors.blue};
    box-shadow: 0px 2px 9px ${({ theme }) => theme.colors.blue};
    border: none;
    width: 30px;
    height: 30px;
    border-radius: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: ${({ theme }) => theme.spacings.l};
  }

  .dialog-title {
    grid-area: title;
    margin-bottom: ${({ theme }) => theme.spacings.l};
    ${HeadingBaseStyles}
    font-weight: 500;
  }
`

export default function Dialog(props: DialogProps) {
  return (
    <React.Fragment>
      {/** The following props are required because we reuse the Heading styles */}
      <DialogStyles as="h6" size="m" color="greenDark" />
      <A11yDialog
        id={props.id}
        dialogRef={props.reference}
        title={props.title}
        classNames={{
          container: 'dialog-container',
          overlay: 'dialog-overlay',
          dialog: 'dialog-content',
          title: 'dialog-title',
          closeButton: 'dialog-close-button',
        }}
        closeButtonContent={<X color={theme.colors.white} />}
      >
        <div>{props.children}</div>
      </A11yDialog>
    </React.Fragment>
  )
}
