// packages/app-next/src/components/FooterNoAuth.vue
<template>
  <footer class="footer-no-auth">
    <a href="https://happyplants.app/#about" target="_blank" rel="noopener" data-cy="footer-about">
      <v-text small color="special">About</v-text>
    </a>
    <a
      href="https://happyplants.app/#contact"
      target="_blank"
      rel="noopener"
      data-cy="footer-contact"
    >
      <v-text small color="special">Contact</v-text>
    </a>
    <a
      href="https://github.com/morkro/happy-plants"
      target="_blank"
      rel="noopener"
      data-cy="footer-os"
    >
      <v-text small color="special">Open Source</v-text>
    </a>
  </footer>
</template>

<script lang="ts">
  import Vue from 'vue'
  export default Vue.extend({
    name: 'FooterNoAuth',
  })
</script>

<style lang="postcss" scoped>
  .footer-no-auth {
    height: 70px;
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    color: var(--brand-white);

    & a {
      text-decoration: none;
    }

    & a:not(:last-of-type) {
      margin-right: calc(var(--base-gap) * 2);
    }
  }
</style>

// packages/app-next-alt/src/components/FooterNoAuth.tsx
import React from 'react'
import styled from 'styled-components'
import { Text } from './Typography'

const footerLinks = [
  {
    href: 'https://happyplants.app/#about',
    dataCy: 'footer-about',
    label: 'About',
  },
  {
    href: 'https://happyplants.app/#contact',
    dataCy: 'footer-contact',
    label: 'Contact',
  },
  {
    href: 'https://github.com/morkro/happy-plants',
    dataCy: 'footer-os',
    label: 'Open source',
  },
]

const FooterContainer = styled.footer`
  height: 70px;
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;

  a {
    text-decoration: none;

    &:hover > * {
      text-decoration: underline;
    }
  }

  a:not(:last-of-type) {
    margin-right: ${(props) => `calc(${props.theme.spacings.m} * 2)`};
  }
`

export default function FooterNoAuth() {
  return (
    <FooterContainer>
      {footerLinks.map((link, index) => (
        <a
          key={link.label + index}
          href={link.href}
          target="_blank"
          rel="noopener noreferrer"
          data-cy={link.dataCy}
        >
          <Text as="span" color="white">
            {link.label}
          </Text>
        </a>
      ))}
    </FooterContainer>
  )
}
