// src/container/overview/PlantPreview.vue
<template>
  <div :class="{ 'plant-preview': true, 'no-photo': !this.imageURL }"
    :style="{ backgroundImage: `url(${imageURL})` }">
    <button @click="deleteElement" class="preview-delete icon">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24">
        <path d="M9 19c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm4 0c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm4 0c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm5-17v2h-20v-2h5.711c.9 0 1.631-1.099 1.631-2h5.315c0 .901.73 2 1.631 2h5.712zm-3 4v16h-14v-16h-2v18h18v-18h-2z"/>
      </svg>
    </button>
    <div @click="handleClick" class="preview-content">
      <div class="preview-headline">
        <h1>{{ name }}</h1>
      </div>
    </div>
  </div>
</template>

<script>
  import router from '@/router'

  export default {
    name: 'PlantPreview',
    props: ['configMode', 'guid', 'name', 'imageURL'],
    methods: {
      handleClick (event) {
        console.log(event.target)
        router.push(`plant/${this.guid}`)
      },
      deleteElement () {
        this.$emit('delete-plant', this.guid)
      }
    }
  }
</script>

<style lang="scss" scoped>
  @import "../../styles/variables";

  .plant-preview {
    width: 100%;
    height: 100%;
    position: relative;
    border-radius: $border-radius;
    overflow: hidden;
    background-size: cover;
    box-shadow: $shadow;

    &.no-photo {
      // TODO: Show default image instead
      background: $grey;
    }
  }

  .preview-delete {
    fill: white;
    position: absolute;
    padding: 10px;
    top: 0;
    right: 0;
    z-index: 1;
  }

  .preview-content {
    width: 100%;
    height: 100%;
    position: relative;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .preview-headline {
    position: absolute;
    color: white;
    width: 100%;
    bottom: 0;
    left: 0;
    padding: 10px;
    font-size: $text-size-small;
    background: linear-gradient(180deg, rgba(0, 0, 0, 0), rgba(0, 0, 0, 1));

    &.inactive,
    &.inactive h1 {
      color: rgba(255, 255, 255, .75);
    }

    h1 {
      color: white;
      font-size: $text-size-base;
      font-weight: 600;
    }
  }
</style>

// packages/app-next-alt/src/components/PlantPreview.tsx
import React from 'react'
import { useDownloadURL } from 'react-firebase-hooks/storage'
import { CameraOff } from 'react-feather'
import { Link } from 'react-router-dom'
import styled, { css } from 'styled-components'
import { theme } from 'theme'
import { getFileRef } from 'services/firebase'
import Spinner from './Spinner'
import { Text } from './Typography'

export interface PlantProps {
  imageUrl?: string | null
  href?: string
  loading?: boolean
  name?: string
  size?: 'm' | 'l'
}

const PlantContainer = styled.div<{ $loading: boolean }>`
  width: 100%;
  height: 100%;
  border-radius: ${({ theme }) => theme.baseRadius};
  overflow: hidden;
  background: ${({ theme }) => theme.colors.white};

  ${({ $loading }) =>
    $loading &&
    css`
      display: flex;
      justify-content: center;
      align-items: center;
      position: relative;

      &::before,
      &::after {
        content: '';
        width: calc(100% - 1.5 * ${({ theme }) => theme.spacings.m});
        height: 16px;
        display: block;
        background: ${({ theme }) => theme.colors.beige};
        border-radius: ${({ theme }) => theme.baseRadius};
        position: absolute;
        bottom: calc(0.5 * ${({ theme }) => theme.spacings.m});
        left: calc(0.75 * ${({ theme }) => theme.spacings.m});
      }

      &::after {
        width: 40%;
        transform: translateY(calc(-100% - 0.5 * ${({ theme }) => theme.spacings.m}));
      }
    }
  `}
`

const StyledLink = styled(Link)`
  display: flex;
  width: 100%;
  height: 100%;
  position: relative;
  align-items: flex-end;
  text-decoration: none;
`

const Label = styled.div<{ gradient: boolean }>`
  text-align: left;
  padding: ${({ theme }) => theme.spacings.m};
  position: relative;
  z-index: 1;
  width: 100%;

  ${({ gradient }) =>
    gradient &&
    css`
      background-image: var(--top-notch-gradient);
    `}
`

const Background = styled.div`
  position: absolute;
  z-index: 0;
  top: 0;
  left: 0;
  right: 0;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;

  img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
`

export default function PlantPreview(props: PlantProps) {
  const { loading = true, href = '', name, imageUrl = '' } = props
  const hasImageUrl = typeof imageUrl === 'string'
  const [downloadedImageUrl, loadingImageUrl] = useDownloadURL(getFileRef(imageUrl as string))
  return (
    <PlantContainer $loading={loading}>
      {loading ? (
        <Spinner color={theme.colors.beigeDark} size={45} />
      ) : (
        <StyledLink to={href}>
          <Label gradient={hasImageUrl}>
            <Text color={hasImageUrl ? 'white' : 'greenDark'}>{name}</Text>
          </Label>
          <Background>
            {hasImageUrl && !loadingImageUrl ? (
              <img loading="lazy" src={downloadedImageUrl} alt={name} title={name} />
            ) : (
              <CameraOff color={theme.colors.beige} size={45} />
            )}
          </Background>
        </StyledLink>
      )}
    </PlantContainer>
  )
}
