// packages/app-next-alt/src/components/AppHeader.tsx
import React from 'react'
import styled from 'styled-components'
import { createTeleporter } from 'react-teleporter'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { ArrowLeft, WifiOff } from 'react-feather'
import { theme, ThemeColors } from 'theme'
import { routePaths } from 'routes'
import useOfflineEvent from 'utilities/useOfflineEvent'
import { Heading } from './Typography'
import VisuallyHidden from './VisuallyHidden'
import AppLogo from './AppLogo'

export const AppHeaderPortal = createTeleporter()

const AppHeaderContainer = styled.header<{ backgroundColor?: AppHeaderColor; isOffline: boolean }>`
  width: 100%;
  height: ${(props) => props.theme.frameWidgetHeight};
  display: flex;
  align-items: center;
  position: sticky;
  top: 0;
  z-index: 1;
  background-color: ${(props) =>
    props.backgroundColor === undefined
      ? 'transparent'
      : props.theme.colors[props.backgroundColor]};

  & > div:last-of-type {
    display: grid;
    align-items: center;
    height: 100%;
    grid-template-columns: auto auto;
    margin-left: auto;
  }

  &::after {
    content: '';
    display: ${({ isOffline }) => (isOffline ? 'block' : 'none')};
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    width: 100%;
    height: 3px;
    background: ${({ theme }) => theme.colors.red};
  }
`

const OfflineIndicator = styled.div`
  position: absolute;
  top: -3px;
  left: 50%;
  transform: translateX(-50%);
  background: ${({ theme }) => theme.colors.red};
  border-radius: 50%;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
  padding: ${({ theme }) => theme.spacings.s};
  aspect-ratio: 1 / 1;
  display: flex;
  justify-content: center;
  align-items: center;

  svg {
    width: 65%;
  }
`

const AppHeaderIcon = styled.div<{ isTransparentBg: boolean }>`
  height: 100%;
  min-width: ${(props) => props.theme.frameWidgetHeight};
  display: flex;
  justify-content: center;
  align-items: center;

  & > a,
  & > button {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
    border: none;
    position: relative;
    background: transparent;

    &::before {
      content: '';
      display: ${({ isTransparentBg }) => {
        return isTransparentBg ? 'block' : 'none'
      }};
      width: 55%;
      aspect-ratio: 1 / 1;
      background: ${(props) => props.theme.colors.white};
      border-radius: 50%;
      position: absolute;
      z-index: -1;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
    }

    &:focus {
      outline: none;
      background: ${(props) => props.theme.colors.white};
      border-bottom-right-radius: ${(props) => props.theme.baseRadius};
    }
  }
`

export const AppHeaderButton = styled.button`
  background: ${({ theme }) => theme.colors.beige};
  border: none;
  cursor: pointer;
  min-width: ${(props) => props.theme.frameWidgetHeight};
  height: 100%;
  position: relative;

  &:focus {
    outline: none;
    background: ${(props) => props.theme.colors.green};

    svg {
      stroke: ${(props) => props.theme.colors.white};
    }
  }
`

export type AppHeaderColor = 'green' | 'blue' | 'beige'

export type AppHeaderProps = React.PropsWithChildren<{
  color?: AppHeaderColor
}>

const textColorMap: Record<AppHeaderColor, Partial<ThemeColors>> = {
  beige: 'greenDark',
  blue: 'white',
  green: 'white',
}

export default function AppHeader(props: AppHeaderProps) {
  const { color, children } = props
  const navigate = useNavigate()
  const location = useLocation()
  const isOffline = useOfflineEvent()
  const textColor = (color && textColorMap[color]) || 'greenDark'
  const hasRouteTitle = React.Children.count(children) > 0
  const showBackButton = location.pathname.split('/').filter(Boolean).length > 1

  return (
    <AppHeaderContainer isOffline={isOffline} backgroundColor={color} role="banner">
      {isOffline ? (
        <OfflineIndicator>
          <WifiOff color={theme.colors.white} />
        </OfflineIndicator>
      ) : null}

      <AppHeaderIcon isTransparentBg={color === undefined}>
        {showBackButton ? (
          <button
            onClick={() =>
              location.pathname === routePaths.login ? navigate(routePaths.root) : navigate(-1)
            }
          >
            <ArrowLeft color={theme.colors[textColor]} aria-hidden="true" focusable="false" />
            <VisuallyHidden>Back</VisuallyHidden>
          </button>
        ) : (
          <Link to={routePaths.root}>
            <AppLogo color={textColor} inverse={textColor !== 'greenDark'} />
            <VisuallyHidden>HappyPlants</VisuallyHidden>
          </Link>
        )}
      </AppHeaderIcon>

      <Heading color={textColor} as="h1" bold>
        {hasRouteTitle ? children : 'HappyPlants'}
      </Heading>

      <AppHeaderPortal.Target />
    </AppHeaderContainer>
  )
}

// src/components/AppHeader.vue
<template>
  <header :class="{ 'app-header': true, transparent }" role="banner">
    <div class="header-inner">
      <div class="header-ctrl">
        <router-link
          v-if="backButton"
          :to="backPath"
          :class="{ 'link-wrapper': true, 'backdrop': isWhite(color) }"
          aria-label="Back">
          <feather-arrow-left :stroke="color" />
        </router-link>
        <slot name="custom-action-left" />
      </div>

      <div @click="scrollTop">
        <slot name="title" />
      </div>

      <div class="header-ctrl">
        <router-link
          v-if="settings === true"
          :to="{ path: '/settings' }"
          :class="{ 'link-wrapper': true, 'backdrop': isWhite(color) }"
          aria-label="Settings">
          <component :is="`feather-${settingsIcon}`" class="header-settings-icon" />
        </router-link>
        <button type="button"
          v-else-if="settings === 'edit'"
          aria-label="Edit"
          :class="settingsClass"
          @click.prevent="settingsOnClick">
          <component :is="`feather-${settingsIcon}`" />
        </button>
        <slot name="custom-action-right" />
      </div>
    </div>
  </header>
</template>

<script>
  export default {
    name: 'AppHeader',

    props: {
      backPath: { type: [String, Object], default: '/' },
      backButton: { type: Boolean, default: false },
      settings: { type: [Boolean, String], default: false },
      settingsIcon: { type: String, default: 'settings' },
      settingsOnClick: { type: Function, default: () => {} },
      scrollUp: { type: Boolean, default: false },
      color: { type: String, default: 'black' },
      transparent: { type: Boolean, default: false }
    },

    components: {
      'feather-arrow-left': () =>
          import('vue-feather-icon/components/arrow-left' /* webpackChunkName: "icons" */),
      'feather-settings': () =>
          import('vue-feather-icon/components/settings' /* webpackChunkName: "icons" */),
      'feather-edit': () =>
        import('vue-feather-icon/components/edit-2' /* webpackChunkName: "icons" */)
    },

    computed: {
      settingsClass () {
        return {
          'edit-data': true,
          'icon': true,
          'inverse': !this.isWhite(this.color),
          'backdrop': this.isWhite(this.color)
        }
      }
    },

    methods: {
      isWhite (color) {
        return color === 'white'
      },
      scrollTop () {
        if (this.scrollUp === false) return

        const duration = 222
        const cosParameter = window.scrollY / 2
        let count = 0
        let oldTimestamp = performance.now()

        function step (newTimestamp) {
          count += Math.PI / (duration / (newTimestamp - oldTimestamp))

          if (count >= Math.PI) window.scrollTo(0, 0)
          if (window.scrollY === 0) return

          window.scrollTo(0, Math.round(cosParameter + cosParameter * Math.cos(count)))
          oldTimestamp = newTimestamp
          window.requestAnimationFrame(step)
        }

        window.requestAnimationFrame(step)
      }
    }
  }
</script>

<style lang="postcss">
  @import "../styles/media-queries";

  .app-header {
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
    background: var(--background-primary);
    max-height: var(--app-header-size);
    width: 100%;
    position: fixed;
    top: 0;
    z-index: 2;
    transition:
      background calc(var(--base-speed) * 2) var(--ease-out-back),
      box-shadow var(--base-speed) var(--ease-out-back);

    & h1 {
      text-transform: uppercase;
      color: var(--text-color-base);
      margin: 0 var(--base-gap);
      padding: var(--base-gap) 0;
    }

    &.transparent {
      background: transparent;
      box-shadow: none;
      transition:
        background calc(var(--base-speed) * 2) var(--ease-out-back),
        box-shadow var(--base-speed) var(--ease-out-back);
    }

    & .edit-data {
      position: relative;
      width: var(--app-header-size);
      min-height: var(--app-header-size);
      display: flex;
      justify-content: center;
      align-items: center;
    }

    &.transparent svg {
      margin: 0;
      width: var(--icon-size-base);
      height: var(--icon-size-base);
      stroke: var(--text-color-button);
    }

    &.transparent svg polygon {
      stroke: var(--text-color-button);
    }
  }

  .app-header .header-inner {
    width: 100%;
    display: flex;
    justify-content: space-between;
    align-items: center;

    @media (--min-desktop-viewport) {
      width: var(--app-desktop-max-width);
      margin: 0 auto;
    }
  }

  .app-header .header-ctrl {
    width: var(--app-header-size);
    min-height: var(--app-header-size);
    height: 100%;

    & .backdrop::before,
    & a:focus::before {
      border-radius: 50%;
      content: "";
      position: absolute;
      top: 50%;
      left: 50%;
      width: calc(var(--icon-size-base) * 2.5);
      height: calc(var(--icon-size-base) * 2.5);
      transform: translate(-50%, -50%);
      z-index: -1;
    }

    & .backdrop::before {
      background: rgba(0, 0, 0, 0.4);
    }

    & a,
    & button {
      width: var(--app-header-size);
      min-height: var(--app-header-size);
      height: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
      position: relative;

      &:focus {
        outline: none;
      }

      &:focus::before {
        background: var(--transparency-black-light);
      }
    }

    & button:focus::after {
      opacity: 0;
    }
  }

  .app-header .header-settings-icon {
    width: var(--icon-size-base);
    height: var(--icon-size-base);
  }
</style>
