// packages/app-next/src/modules/welcome/views/Welcome.vue
<template>
  <div class="screen-welcome">
    <main>
      <div class="welcome-illustration">
        <welcome-illustration data-cy="illustration" focusable="false" />
        <div>
          <v-text color="inactive" data-cy="welcome-text">
            Keep track of your<br />houseplants' well-being.
          </v-text>
        </div>
      </div>
      <div class="welcome-actions">
        <router-link to="/login" class="btn border" data-cy="action-login">
          Login
        </router-link>
        <router-link to="/onboarding" class="btn yellow" data-cy="action-onboarding">
          Getting started
        </router-link>
      </div>
    </main>
    <footer>
      <v-text small color="special" data-cy="footer-about">About</v-text>
      <v-text small color="special" data-cy="footer-contact">Contact</v-text>
      <v-text small color="special" data-cy="footer-os">Open Source</v-text>
    </footer>
  </div>
</template>

<script lang="ts">
  import Vue from 'vue'
  import Illustration from '@/modules/welcome/components/Illustration.vue'
  export default Vue.extend({
    name: 'Welcome',
    components: {
      'welcome-illustration': Illustration,
    },
  })
</script>

<style lang="postcss" scoped>
  .screen-welcome {
    width: 100%;
    background-image: url('../assets/welcome-background.svg');
    background-repeat: no-repeat;
    background-size: calc(100% + 2px);
    background-position: bottom;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 0 var(--base-gap);
  }

  .screen-welcome main {
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    flex-direction: column;
    justify-content: space-between;

    & .welcome-illustration {
      margin-top: calc(3.25 * var(--base-gap));
      text-align: center;

      & p {
        transform: translateY(calc(var(--base-gap) * -1));
        background: var(--brand-beige);
        display: inline;
        box-shadow: 3px 0 0 var(--brand-beige), -3px 0 0 var(--brand-beige);
      }
    }

    & .welcome-actions {
      width: 100%;
      display: grid;
      grid-template-columns:
        calc(50% - (var(--base-gap) / 2))
        calc(50% - (var(--base-gap) / 2));
      grid-column-gap: var(--base-gap);

      & .btn.yellow {
        box-shadow: 0 1px 2px var(--brand-green-dark);
      }
    }
  }

  .screen-welcome footer {
    height: 70px;
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    color: var(--brand-white);

    & .text:not(:last-of-type) {
      margin-right: calc(var(--base-gap) * 2);
    }
  }
</style>

// packages/app-next-alt/src/pages/Welcome.tsx
import React from 'react'
import styled, { createGlobalStyle, css } from 'styled-components'
import { routePaths } from 'routes'
import { ButtonLink } from 'components/Button'
import { Text } from 'components/Typography'
import Layout, { AppContent, BaseLayout } from 'components/Layout'
import WelcomeIllustration from 'components/WelcomeIllustration'

const WelcomeGlobalStyle = createGlobalStyle`
  #root ${BaseLayout} {
    background-image: url('assets/welcome-background.svg');
    background-repeat: no-repeat;
    background-size: calc(100% + 2px);
    background-position: bottom;
  }

  #root ${AppContent} {
    justify-content: space-between;
  }
`

const IllustrationContainer = styled.div`
  ${({ theme }) => css`
    margin-top: calc(3.25 * ${theme.spacings.l});
    text-align: center;

    & p {
      transform: translateY(calc(${theme.spacings.m} * -1));
      background: ${theme.colors.beige};
      display: inline;
      box-shadow: 3px 0 0 ${theme.colors.beige}, -3px 0 0 ${theme.colors.beige};
      border-radius: ${theme.baseRadius};
    }
  `}
`

const WelcomeActions = styled.div`
  ${({ theme }) => css`
    width: 100%;
    display: grid;
    grid-template-columns:
      calc(50% - (${theme.spacings.m} / 2))
      calc(50% - (${theme.spacings.m} / 2));
    grid-column-gap: ${theme.spacings.m};

    a[href='${routePaths.onboarding}'] {
      box-shadow: 0 1px 2px ${theme.colors.greenDark};
    }
  `}
`

export default function Welcome() {
  return (
    <React.Fragment>
      <WelcomeGlobalStyle />

      <Layout isPrivateRoute={false} withAppMenu={false}>
        <IllustrationContainer>
          <WelcomeIllustration data-cy="illustration" />
          <div>
            <Text color="beigeDark" data-cy="welcome-text">
              Keep track of your
              <br />
              houseplants&apos; well-being.
            </Text>
          </div>
        </IllustrationContainer>

        <WelcomeActions>
          <ButtonLink border to={routePaths.login} data-cy="action-login">
            Login
          </ButtonLink>
          <ButtonLink variant="warning" to={routePaths.onboarding} data-cy="action-onboarding">
            Getting started
          </ButtonLink>
        </WelcomeActions>
      </Layout>
    </React.Fragment>
  )
}
